spring:
  boot:
    admin:
      client:
        url: http://localhost:4444

management:
  endpoints:
    web:
      exposure:
        inclide: "*"

message: "This is a test message from config server"
